### ISSUE TITLE
Need directions

### ISSUE THREAD

**Issue by cpgb85** [3screens/cordova-brother-label-printer#30]
This page has no examples or directions on how to use this in the app.

**Comment by gordol** [comment]
https://github.com/gordol/cordova-brother-label-printer#usage

**Comment by cpgb85** [comment]
pointing to your own project that  has almost no documentation on how to use it is not proof of having documentation. Give us some test samples.

**Comment by gordol** [comment]
It is pretty well documented, if I say so myself. What more do you want?

There are only 3 methods.

findNetworkPrinters()
printViaSDK()
sendUSBConfig()

**findNetworkPrinters** must be called before printViaSDK. It takes no parameters and returns two parameters, one is a boolean (whether a printer was found or not), and the other is a list of found printers. To print, all that's needed are the IP and MAC of the target printer.

Currently, the last printer that is found will be the one targetted due to the way we're looping over the netPrinters array. This plugin could be extended to allow the user to select which printer they want to connect with... If this is desired, let me know, and I'll address when I get a chance, or better yet, send a pull request. The best way would either be to pass the printer IP/MAC to the printViaSDK method, or perhaps you could just pass an index to select the desired printer from the netPrinters list.

**printViaSDK** takes one parameter, which is a base64 encoded bitmap image. The result should be a status code that is passed directly from the SDK. The status codes are documnted in the Brother SDK Appendix in section 4.2.2.5.Error Code. If everything works, the response should be "ERROR_NONE".

**sendUSBConfig** calls the Brother SDK's printFile method. The expected input is a string containing raw print commands, which is written to a temporary file in the app cache directory, and is then sent to the printFile method and deleted afterwards. You will need a device that supports USB-OTG and a USB-OTG cable. On first run the app will request USB permissions, and it should be saved after that for subsequent prints. As-is, this method is used to send raw commands in PCL (Printer Control Language) to the printer... For example, to configure the network settings of the printer, etc... You will need to reach out to Brother for documentation of the PCL commands. You can probably find them by searching for "Brother Printer Command Reference" and appending your model number. This method could be extended easily to accept other types of file input, so you could, for example, print JPG images, etc...



Seriously, this explanation is considerably longer and more complex than the code, by a large factor.

https://github.com/gordol/cordova-brother-label-printer/blob/master/www/printer.js

Just read the code.

**Comment by cpgb85** [comment]
I love reading directions by programmers.

**Comment by gordol** [comment]
better get used to it haha
